name: godog-http-api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Turn on backend
        working-directory: assets
        run: ./test_server/bin/linux/amd64/user_crud &

      - name: Run e2e tests
        run: |
          make download-dependencies
          make env
          godog --concurrency=2 --format=progress --random