name: godog-example-setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Turn on backend
        working-directory: bin
        run: ./linux/amd64/user_crud &

      - name: Run e2e tests
        run: |
          go mod download
          go install github.com/cucumber/godog/cmd/godog@v0.12.0
          echo "GODOG_DEBUG=false" > .env
          godog --version
          godog --concurrency=2 --format=progress --random