name: godog_example_setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Turn on backend
        working-directory: bin
        run: ./users_crud

      - name: Run e2e tests
        run: |
          pwd
          go mod download
          echo " " > .env
          sleep 10
          mkdir cucumber
          godog --version
          godog